ALTER TABLE TB_PAY
ADD (PAY_POINT NUMBER,
     PAY_SUMPOINT NUMBER);
     
    
    --유저포인트 합계 테스트
 SELECT SUM(PAY_POINT) AS TOTAL_POINT
	    FROM TB_PAY
	    WHERE USER_SEQ = 706
	    GROUP BY USER_SEQ
	    HAVING SUM(PAY_POINT) >= 0;