	INSERT INTO TB_BOOK_RENT
		(RENT_SEQ, USER_SEQ, BOOK_SEQ, RENT_DATE, RENT_RETURN_DATE, RENT_STATUS)
		SELECT SQ_RENT.NEXTVAL, U.USER_SEQ, B.BOOK_SEQ, SYSDATE, SYSDATE + 7, 'Y'
		FROM TB_USER U
		CROSS JOIN TB_BOOK B
		WHERE U.USER_SEQ = 2
		  AND B.BOOK_SEQ = 1;
		  
		 
INSERT INTO BOOK.TB_RESVE
(RESVE_SEQ, USER_SEQ, BOOK_SEQ, RESVE_STEP, RESVE_STATUS)
VALUES(100, 1, 48, 1, 'R');
