CREATE SEQUENCE SQ_BOOK START WITH 501 INCREMENT BY 1;

ALTER TABLE TB_USER
ADD (NAVER_KEY VARCHAR2(1000),
     KAKAO_KEY VARCHAR2(1000));
     
ALTER TABLE TB_USER
DROP COLUMN SNS_KEY;


  SELECT COUNT(*)
   FROM TB_USER
   WHERE USER_NAME = '김영진'
   			AND USER_EMAIL = 'kt2015@naver.com'
   			AND USER_PHONE = '010-9246-5758'
   			AND NAVER_KEY IS NOT NULL;