    SELECT B.BOOK_SEQ, R.RENT_SEQ, U.USER_NAME AS USER_NAME, B.BOOK_TITLE AS BOOK_TITLE, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS
    FROM (
        SELECT R.*, ROW_NUMBER() OVER(ORDER BY RENT_DATE DESC) AS RN
        FROM BOOK.TB_BOOK_RENT R
    ) AS TempTable
    INNER JOIN BOOK.TB_USER U ON TempTable.USER_SEQ = U.USER_SEQ
    INNER JOIN BOOK.TB_BOOK B ON TempTable.BOOK_SEQ = B.BOOK_SEQ
    WHERE RN BETWEEN 1 AND 5
    ORDER BY RENT_DATE DESC;
    
   SELECT B.BOOK_SEQ, R.RENT_SEQ, U.USER_NAME AS USER_NAME, B.BOOK_TITLE AS BOOK_TITLE, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS
FROM (
    SELECT R.*, ROWNUM AS RN
    FROM BOOK.TB_BOOK_RENT R
    WHERE ROWNUM <= 5 -- 최대 행 수
    ORDER BY RENT_DATE DESC
) TempTable
INNER JOIN BOOK.TB_USER U ON TempTable.USER_SEQ = U.USER_SEQ
INNER JOIN BOOK.TB_BOOK B ON TempTable.BOOK_SEQ = B.BOOK_SEQ
ORDER BY RENT_DATE DESC;


    SELECT B.BOOK_SEQ, R.RENT_SEQ, U.USER_NAME AS USER_NAME, B.BOOK_TITLE AS BOOK_TITLE, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS
    FROM BOOK.TB_BOOK_RENT R
    INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
    INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ;

    
   SELECT ID, NAME, EMAIL, AUTH, DELFLAG, JOINDATE 
	FROM (
			SELECT ID, NAME, EMAIL,
					AUTH, DELFLAG, JOINDATE,
			ROW_NUMBER()OVER(ORDER BY JOINDATE DESC) RN
			FROM USERINFO u
		)
		WHERE RN BETWEEN #{first} AND #{last}

SELECT B.BOOK_SEQ, R.RENT_SEQ, U.USER_NAME AS USER_NAME, B.BOOK_TITLE AS BOOK_TITLE, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS
FROM (
    SELECT R.USER_SEQ AS ID, U.USER_NAME AS NAME, U.USER_EMAIL AS EMAIL,
           NULL AS AUTH, NULL AS DELFLAG, R.RENT_DATE AS JOINDATE,
           ROW_NUMBER() OVER (ORDER BY R.RENT_DATE DESC) AS RN
    FROM BOOK.TB_BOOK_RENT R
    INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
    INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ
) TempTable
WHERE RN BETWEEN 1 AND 5;


SELECT SEQ, NAME, BOOK_TITLE, RENT_DATE, RENT_RETURN_DATE, RENT_STATUS
FROM (
    SELECT R.RENT_SEQ AS SEQ, U.USER_NAME AS NAME, B.BOOK_TITLE, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS,
           ROW_NUMBER() OVER (ORDER BY R.RENT_DATE DESC) AS RN
    FROM BOOK.TB_BOOK_RENT R
    INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
    INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ
) TempTable
WHERE RN BETWEEN 1 AND 5;



SELECT R.RENT_SEQ, R.USER_SEQ, R.BOOK_SEQ, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS,
           U.USER_NAME AS user_name, B.BOOK_TITLE AS book_title
    FROM TB_BOOK_RENT R
    INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
    INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ
    WHERE U.USER_SEQ = #{user_seq}
    ORDER BY RENT_DATE DESC
    
    
SELECT SEQ, USER_SEQ, BOOK_SEQ, RENT_DATE, RENT_RETURN_DATE, RENT_STATUS,
       USER_NAME AS user_name, BOOK_TITLE AS book_title
FROM (
    SELECT R.RENT_SEQ AS SEQ, R.USER_SEQ, R.BOOK_SEQ, R.RENT_DATE, R.RENT_RETURN_DATE, R.RENT_STATUS,
           U.USER_NAME, B.BOOK_TITLE,
           ROW_NUMBER() OVER (ORDER BY R.RENT_DATE DESC) AS RN
    FROM TB_BOOK_RENT R
    INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
    INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ
    WHERE R.USER_SEQ = 1
) TempTable
WHERE RN BETWEEN 1 AND 40;






SELECT
    U.USER_NAME AS user_name,
    B.BOOK_SEQ AS book_seq,
    B.BOOK_TITLE AS book_title,
    R.RESVE_SEQ,
    R.RESVE_STATUS,
    (SELECT COUNT(DISTINCT RESVE_STEP) FROM BOOK.TB_RESVE WHERE BOOK_SEQ = B.BOOK_SEQ AND RESVE_STEP IS NOT NULL AND RESVE_STEP <= R.RESVE_STEP) AS RESVE_STEP
FROM BOOK.TB_RESVE R
INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ
WHERE U.USER_SEQ = 701
ORDER BY RESVE_SEQ DESC;


SELECT RESVE_SEQ, user_name, book_title, RESVE_STATUS, RESVE_STEP
FROM (
    SELECT
        user_name,
        book_seq,
        book_title,
        RESVE_SEQ,
        RESVE_STATUS,
        RESVE_STEP,
        ROWNUM AS RN
    FROM (
        SELECT
            U.USER_NAME AS user_name,
            B.BOOK_SEQ AS book_seq,
            B.BOOK_TITLE AS book_title,
            R.RESVE_SEQ,
            R.RESVE_STATUS,
            (
                SELECT COUNT(DISTINCT RESVE_STEP)
                FROM BOOK.TB_RESVE R2
                WHERE R2.BOOK_SEQ = B.BOOK_SEQ
                AND R2.RESVE_STEP IS NOT NULL
                AND R2.RESVE_STEP <= R.RESVE_STEP
            ) AS RESVE_STEP
        FROM BOOK.TB_RESVE R
        INNER JOIN BOOK.TB_USER U ON R.USER_SEQ = U.USER_SEQ
        INNER JOIN BOOK.TB_BOOK B ON R.BOOK_SEQ = B.BOOK_SEQ
        WHERE U.USER_SEQ = 701
        ORDER BY R.RESVE_SEQ DESC
    )
)
WHERE RN BETWEEN 1 AND 10; 
