-- 로그인 구현
SELECT USER_SEQ,USER_EMAIL,USER_PHONE,USER_BIRTH,JOINDATE,USER_NAME,USER_AUTH,USER_GENDER
	FROM TB_USER
	WHERE USER_EMAIL = TEST
	AND USER_PASSWORD = user_passwor
</select>

--일반 회원가입
INSERT INTO TB_USER
(USER_SEQ,USER_EMAIL,USER_PASSWORD,USER_NAME,USER_PHONE,USER_BIRTH,
USER_AUTH,USER_DELFLAG,JOINDATE,SNS_KEY,USER_GENDER)
VALUES ('53','test11@test.com','440138','김영진','010-1111-3333','1992-10-26',
		'U','N',SYSDATE,NULL,'M');

-- 소셜로그인 시도 시 사용자가 기존 아이디가 있는지 확인하는 쿼리
	SELECT USER_EMAIL
	FROM TB_USER
	WHERE SNS_KEY = 'test';

-- 소셜 네이버 로그인(기존회원이 아닐 경우) 회원가입
INSERT INTO TB_USER
(USER_SEQ,USER_EMAIL,USER_PASSWORD,USER_NAME,USER_PHONE,USER_BIRTH,
USER_AUTH,USER_DELFLAG,JOINDATE,SNS_KEY*네이버*,USER_GENDER)
VALUES ('55','test13@test.com','440138','김영진2','010-1111-3333','1992-10-26',
		'U','N',SYSDATE,'NV82MVC9DSMCJ','M');
	
-- 소셜 카카오 로그인(기존회원이 아닐 경우) 회원가입
INSERT INTO TB_USER
(USER_SEQ,USER_EMAIL,USER_PASSWORD,USER_NAME,USER_PHONE,USER_BIRTH,
USER_AUTH,USER_DELFLAG,JOINDATE,SNS_KEY*카카오*,USER_GENDER)
VALUES ('55','test13@test.com','440138','김영진2','010-1111-3333','1992-10-26',
		'U','N',SYSDATE,'NV82MVC9DSMCJ','M');	

--일반회원 네이버 소셜 연동

UPDATE TB_USER SET SNS_KEY(네이버) = #{네이버컬럼}
WHERE EMAIL =#{email};

--일반회원 카카오 소셜 연동

UPDATE TB_USER SET SNS_KEY(카카오) = #{카카오컬럼}
WHERE EMAIL =#{email};
